sudo: required
dist: trusty

before_script:
  - bash -xve ./test/travis_ros_install.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_build_consai.bash
  - source ~/catkin_ws/devel/setup.bash

script:
  - rostest ai_core test_simulator.launch
